### ISSUE TITLE
Please consider renaming the repository

### ISSUE THREAD

**Issue by unixorn** [igor9silva/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it `igorsilva` after the `.zsh-theme` file.

Thanks!

**Comment by igor9silva** [comment]
Hi, thanks for reaching. Nice work with the awesome repo!

Made it `igorsilva-zsh-theme`, but can't you just refer to it as `igorsilva` and the repo be just `zsh-theme` since it's inside my user namespace?

`igorsilva/zsh-theme` versus `igorsilva/igorsilva-zsh-theme`

**Comment by unixorn** [comment]
Sure!
